language: go
go:
  - "1.15"
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
script:
  - go build
  - go test -v ./...
  - $(go env GOPATH)/bin/golangci-lint run